### ISSUE TITLE
Use NLTK to fetch list of verbs

### ISSUE THREAD

**Issue by felipecrs** [mristin/opinionated-commit-message#139]
I believe there's no need to hardcode. [NLTK](https://www.nltk.org/) provides this information.

Here's one example implementation for the exact same purpose:

https://github.com/coala/coala-bears/pull/315/files

**Comment by felipecrs** [comment]
This may help: https://github.com/extremeheat/JSPyBridge

**Comment by mristin** [comment]
Hi @felipecrs ! Thanks for the suggestion!

I considered NLP some time ago, but it brought some problems of its own:
* Complicated / heavy to deploy and
* Difficult to reproduce on a local machine (originally, we maintained a PowerScript mimicking the action).

If you want this functionality, probably it is worth looking into ChatGPT. Otherwise, feel free of course to fork this action and add NLP to it.
