### ISSUE TITLE
Check commits instead of PR text for pull requests

### ISSUE THREAD

**Issue by krahlro-sick** [mristin/opinionated-commit-message#28]
The tool should check the commits that are part of a PR instead of the PR text if it is executed for a pull request ([example run](https://github.com/admin-shell-io/aasx-package-explorer/actions/runs/161641055).

**Comment by krahlro-sick** [comment]
As discussed via mail:  It might make sense to also check the PR title if there are multiple commits as it is included in the squashed commit message ([example](https://github.com/admin-shell-io/aasx-package-explorer/commit/dabb94ddec11272a3568c1e908e69dea4236c0bd)).

**Comment by mristin** [comment]
Please see: https://github.com/mristin/opinionated-commit-message/pull/30#issuecomment-655951312

I'll add a clarification in the readme.

**Comment by mristin** [comment]
The relevant section in the readme is here: https://github.com/mristin/opinionated-commit-message#known-issue

I'll leave this issue open to gauge how many people need this feature.

**Comment by mristin** [comment]
Closing since no new messages in a while.

**Comment by 1david5** [comment]
hey @mristin, I just noticed that when the action gets triggered by `push` it only checks the last commit in the PR. On the other hand. When it's triggered by a pull_request it checks the first commit in the PR. 

Is there any way to trigger the action to check all the commits in the PR?

**Comment by mristin** [comment]
Hi @1david5 ,
I'll re-visit commit-message-checker and see how they check the commits. Please have patience, though, as I am currently pretty tight on time.

**Comment by 1david5** [comment]
That sounds great. Thank you for the update and this action 👍

**Comment by 1david5** [comment]
Hi @mristin,
Yeah I understand, I'm pretty much the same but still gonna try to submit the PR with a fix since still want to use the action. Thank you 👍

**Comment by mristin** [comment]
Hi @1david5 ,
Please apologize again. I am still battling with the same things as in June. I hoped that one phase of the project would have finished during summer, but here we are...

At this point I can't really promise any timeline when I'd be able to look into this. If you can scrap some time, please do go ahead and make a PR. I promise to review it & support you as much I can.

**Comment by mristin** [comment]
@johnboyes @1david5 I finally have some time to fix this.

I thought to check both the body of pull request *and* the commit messages. I'd also add a flag, `dont_check_commit_messages`, and release a major version.

What do you think?

**Comment by johnboyes** [comment]
Hi @mristin, thanks for working on this.  For the flag, I think a positive flag (rather than a negative flag starting with `dont`) would be more intuitive to use, called something like `check_pr_commits`.  I think it's important to include `pr` in the flag name, otherwise the name would be confusing. 
In terms of checking the pull request body, I'd propose a separate flag for that, called something like `check_pr_body`.  HTH, John

**Comment by Fryuni** [comment]
Hi everyone! I'm working on this issue at the moment, so as an update.

The event received by the GH action doesn't include the commits of the PR, it includes the URL where those commits can be retrieved (following HATEOAS). Problem is that the commits URL has the same privacy as the repo, so for private repos this action would need the `GITHUB_TOKEN` secret in order to validate the commit messages like so:

```yaml
- uses: mristin/opinionated-commit-message@v3.0.1
  with:
    github-token: ${ secrets.GITHUB_TOKEN }
```

Public repos don't have such requirement.

I'll try to send a PR soon with this.

**Comment by Fryuni** [comment]
PR opened, please try it out!
